### ISSUE TITLE
Select and upload dataset

### ISSUE THREAD

**Issue by 7Zenox** [projectayre/ayre#1]
Select datasets for the following models:

- [x] ~~#4~~
- [x] #5
- [x] #15

**Comment by hauntedcupoftea** [comment]
#4 had a potential fix but has been rejected.
#5 will not be uploaded.

**Comment by hauntedcupoftea** [comment]
#4 has been replaced with another:
- [ ] Image Semantic Segmentation.

**Comment by hauntedcupoftea** [comment]
also note: no datasets henceforth will be uploaded because of a mix of the terms of use and the size of the datasets itself. I will be working on them locally, and can give you a copy if you want one.

**Comment by hauntedcupoftea** [comment]
Datasets are done. Semantic Segmentation training pipeline is also complete, but the deployment one still remains.
