### ISSUE TITLE
Sentiment analysis

### ISSUE THREAD

**Issue by hauntedcupoftea** [projectayre/ayre#4]

**Comment by hauntedcupoftea** [comment]
Selected this dataset: [https://datasets.simula.no/image-sentiment/](https://datasets.simula.no/image-sentiment/) for now. It has the most detailed emotional information we have seen so far. However, this dataset can prove biased because all images are related to disasters.

**Comment by 7Zenox** [comment]
These are worth exploring:

- [ ] https://www.ee.columbia.edu/ln/dvmm/vso/download/flickr_dataset.html
- [ ] https://data.world/crowdflower/image-sentiment-polarity

**Comment by hauntedcupoftea** [comment]
#8 has a valid solution, so this isn't really needed. We need to get to actually making the project, and I doubt we'll find a dataset that covers the range of emotions as well as this.

**Comment by hauntedcupoftea** [comment]
Reopening this because @7Zenox and @Dekode1859 want to potentially replace the dataset with something else. What we have discussed so far:
- Current dataset is small and niche, and has a low of bias against "general" and "social media" data.
- However, from a totally research based stand, pre-processing the 26 output labels results in a more novel approach that we can add to academic research
- Someone was talking about alt datasets and their importance, as well as potential for better output. Can't remember who, but please just talk this out and find a fix because I'm slowly losing patience with all my work.

**Comment by hauntedcupoftea** [comment]
This task will now be done via a modification of the image semantic segmentation. Had a small eureka moment.
